-- Nothing to seed.
--
-- The catalogue used to be generated here from lib/books.ts. It now lives in
-- the books table, put there by supabase/migrations/20260921090300_backfill_books.sql,
-- and is edited from the admin dashboard. A local `supabase db reset` replays
-- that migration and comes up with the same books as production.
