-- Orders: one row per checkout attempt.
--
-- The lifecycle is created -> paid -> (fulfilled, emailed), or created ->
-- failed. Both the verify endpoint and the Razorpay webhook can move an
-- order to 'paid', so every transition must be written as a conditional
-- UPDATE and be safe to replay.
--
-- id and download_token are TEXT UUIDs generated by application code
-- (crypto.randomUUID() in the Worker) at insert time — D1/SQLite has no
-- server-side UUID generator, so there is no DEFAULT for either column.

CREATE TABLE orders (
  id                  TEXT PRIMARY KEY,
  book_slug           TEXT NOT NULL REFERENCES books (slug),
  amount_paise        INTEGER NOT NULL CHECK (amount_paise > 0),
  currency            TEXT NOT NULL DEFAULT 'INR',
  status              TEXT NOT NULL DEFAULT 'created' CHECK (status IN ('created', 'paid', 'failed', 'refunded')),
  razorpay_order_id   TEXT NOT NULL UNIQUE,
  razorpay_payment_id TEXT UNIQUE,
  buyer_email         TEXT,
  buyer_phone         TEXT,
  download_token      TEXT NOT NULL UNIQUE,
  download_count      INTEGER NOT NULL DEFAULT 0 CHECK (download_count >= 0),
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  paid_at             TEXT,
  fulfilled_at        TEXT,
  email_sent_at       TEXT
);

CREATE INDEX orders_buyer_email_idx ON orders (lower(buyer_email));
CREATE INDEX orders_status_idx      ON orders (status);
CREATE INDEX orders_book_slug_idx   ON orders (book_slug);
CREATE INDEX orders_created_at_idx  ON orders (created_at DESC);
